use libseccomp::ScmpAction;
use libseccomp::ScmpFilterContext;
use libseccomp::ScmpSyscall;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum SeccompError {
    #[error("failed to initialize seccomp context: {0}")]
    Init(String),
    #[error("failed to add syscall rule: {0}")]
    AddSyscall(String),
    #[error("failed to load seccomp filter: {0}")]
    Load(String),
}

pub type Result<T> = std::result::Result<T, SeccompError>;

pub fn apply_seccomp_filter() -> Result<()> {
    let mut ctx = ScmpFilterContext::new(ScmpAction::KillProcess)
        .map_err(|e| SeccompError::Init(e.to_string()))?;

    allow_core_syscalls(&mut ctx)?;

    ctx.load().map_err(|e| SeccompError::Load(e.to_string()))?;

    Ok(())
}

const ALLOW_SYSCALLS: &[&str] = &[
    "pread",
    "pwrite",
    "wait",
    "eventfd",
    "prlimit",
    "preadv",
    "preadv2",
    "inotify_rm_watch",
    "inotify_init",
    "fadvise",
    "read",
    "readv",
    "write",
    "writev",
    "pwritev",
    "pread64",
    "pwrite64",
    "open",
    "openat",
    "close",
    "close_range",
    "stat",
    "lstat",
    "fstat",
    "access",
    "faccessat",
    "readlink",
    "readlinkat",
    "getcwd",
    "getdents64",
    "mkdir",
    "rmdir",
    "unlink",
    "link",
    "symlink",
    "rename",
    "chmod",
    "fchmod",
    "chown",
    "fchown",
    "lchown",
    "mount",
    "umount",
    "umount2",
    "truncate",
    "ftruncate",
    "fallocate",
    "mmap",
    "mprotect",
    "munmap",
    "mremap",
    "msync",
    "brk",
    "madvise",
    "dup",
    "dup2",
    "dup3",
    "pipe",
    "pipe2",
    "select",
    "poll",
    "epoll_create",
    "epoll_create1",
    "epoll_ctl",
    "epoll_wait",
    "epoll_pwait",
    "epoll_pwait2",
    "pselect6",
    "ppoll",
    "rt_sigaction",
    "rt_sigprocmask",
    "rt_sigsuspend",
    "rt_sigreturn",
    "sigaltstack",
    "kill",
    "getsockopt",
    "setsockopt",
    "getpeername",
    "getsockname",
    "socket",
    "socketpair",
    "bind",
    "listen",
    "accept",
    "connect",
    "shmget",
    "shmat",
    "shmctl",
    "clock_gettime",
    "clock_getres",
    "clock_nanosleep",
    "gettimeofday",
    "time",
    "nanosleep",
    "alarm",
    "setitimer",
    "getpid",
    "gettid",
    "getppid",
    "getpgrp",
    "getsid",
    "getuid",
    "getgid",
    "geteuid",
    "getegid",
    "setuid",
    "setgid",
    "seteuid",
    "setegid",
    "setreuid",
    "setregid",
    "getgroups",
    "setgroups",
    "getresuid",
    "getresgid",
    "setresuid",
    "setresgid",
    "getpgid",
    "setpgid",
    "setsid",
    "setns",
    "uname",
    "sysinfo",
    "syslog",
    "getrlimit",
    "setrlimit",
    "getrusage",
    "umask",
    "prctl",
    "prlimit64",
    "getrandom",
    "execve",
    "vfork",
    "exit",
    "exit_group",
    "wait4",
    "waitid",
    "personality",
    "arch_prctl",
    "recvfrom",
    "sendto",
    "recvmsg",
    "sendmsg",
    // glibc startup / threading
    "set_tid_address",
    "set_robust_list",
    "rseq",
    "futex",
    "futex_waitv",
    "clone",
    "clone3",
    "tgkill",
    "tkill",
    // common I/O
    "ioctl",
    "lseek",
    "sendfile",
    "copy_file_range",
    "fcntl",
    "flock",
    "fadvise64",
    "sync",
    "fsync",
    "fdatasync",
    "syncfs",
    // file ops
    "newfstatat",
    "statx",
    "openat2",
    "mkdirat",
    "unlinkat",
    "renameat",
    "renameat2",
    "linkat",
    "symlinkat",
    "fchmodat",
    "fchownat",
    "faccessat2",
    "getdents",
    "inotify_init1",
    "inotify_add_watch",
    "eventfd2",
    "io_uring_setup",
    "io_uring_enter",
    "io_uring_register",
    "pidfd_open",
    "timerfd_create",
    "timerfd_settime",
    "timerfd_gettime",
    "signalfd4",
    "accept4",
    "recvmmsg",
    "sendmmsg",
    // terminal / interactive shell
    "setfsuid",
    "setfsgid",
    "sched_getparam",
    "sched_setscheduler",
    "sched_getscheduler",
    "sched_yield",
    "sched_getaffinity",
    "sched_setaffinity",
    "pkey_alloc",
    "capget",
    "capset",
    "chdir",
    "fchdir",
    "chroot",
    "pivot_root",
    "statfs",
    "fstatfs",
    "getxattr",
    "lgetxattr",
    "fgetxattr",
    "listxattr",
    "llistxattr",
    "flistxattr",
    "memfd_create",
    "memfd_secret",
    "mlock",
    "mlock2",
    "munlock",
    "mlockall",
    "munlockall",
    "splice",
    "tee",
    "vmsplice",
    // time-related
    "utimensat",
    "utimes",
    "utime",
    "clock_settime",
    "settimeofday",
];

fn allow_core_syscalls(ctx: &mut ScmpFilterContext) -> Result<()> {
    for name in ALLOW_SYSCALLS.iter() {
        add_syscall_allow(ctx, name)?;
    }

    Ok(())
}

fn add_syscall_allow(ctx: &mut ScmpFilterContext, name: &str) -> Result<()> {
    if let Ok(syscall) = ScmpSyscall::from_name(name) {
        ctx.add_rule(ScmpAction::Allow, syscall)
            .map_err(|e| SeccompError::AddSyscall(e.to_string()))?;
    }
    Ok(())
}

#[cfg(test)]
#[test]
fn test_allow_core_syscalls() {
    // strace -f -o ./strace.log
    // cat ./strace.log | grep -oE '^[0-9]+ [a-z_]+' | awk '{print $2}' | sort | uniq -c | sort -rn

    let needed_calls = [
        "futex",
        "sched_yield",
        "openat",
        "read",
        "close",
        "statx",
        "madvise",
        "lseek",
        "fstat",
        "pread",
        "stat",
        "newfstatat",
        "rt_sigaction",
        "mmap",
        "rt_sigprocmask",
        "clock_gettime",
        "mprotect",
        "munmap",
        "write",
        "epoll_pwait",
        "getpid",
        "getdents",
        "ioctl",
        "rt_sigreturn",
        "tgkill",
        "epoll_ctl",
        "brk",
        "fcntl",
        "rt_sigsuspend",
        "access",
        "recvfrom",
        "pwrite",
        "timerfd_settime",
        "set_robust_list",
        "rseq",
        "clone",
        "prlimit",
        "getuid",
        "readlink",
        "geteuid",
        "execve",
        "getgid",
        "dup",
        "prctl",
        "getegid",
        "sched_getaffinity",
        "epoll_wait",
        "getrandom",
        "sigaltstack",
        "unlink",
        "capget",
        "gettid",
        "getsockopt",
        "exit",
        "getcwd",
        "getsockname",
        "socketpair",
        "set_tid_address",
        "arch_prctl",
        "wait",
        "sendto",
        "pipe",
        "exit_group",
        "rmdir",
        "lstat",
        "writev",
        "poll",
        "pwritev",
        "sched_setscheduler",
        "connect",
        "setsockopt",
        "uname",
        "close_range",
        "clock_nanosleep",
        "chdir",
        "vfork",
        "pidfd_open",
        "epoll_create",
        "socket",
        "getgroups",
        "eventfd",
        "mkdir",
        "getppid",
        "fsync",
        "io_uring_setup",
        "mremap",
        "recvmsg",
        "io_uring_enter",
        "setitimer",
        "rename",
        "timerfd_create",
        "link",
        "ftruncate",
        "chmod",
        "umask",
        "bind",
        "open",
        "getresuid",
        "getresgid",
        "getpgrp",
        "ppoll",
        "memfd_create",
        "truncate",
        "sysinfo",
        "readlinkat",
        "preadv",
        "kill",
        "inotify_rm_watch",
        "inotify_init",
        "inotify_add_watch",
        "fchdir",
        "fallocate",
        "fadvise",
    ];
    for &name in needed_calls.iter() {
        let allow = ALLOW_SYSCALLS.iter().any(|&x| name == x);
        assert!(allow, "syscall {} is not allowed", name);
    }
}
